// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sierra.Model;

namespace Sierra.Model.Migrations
{
    [DbContext(typeof(SierraDbContext))]
    partial class SierraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sierra.Model.Fork", b =>
                {
                    b.Property<Guid>("ForkVstsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SourceRepositoryName")
                        .IsRequired();

                    b.Property<string>("TenantId");

                    b.Property<string>("TenantName")
                        .IsRequired();

                    b.HasKey("ForkVstsId");

                    b.HasIndex("TenantId");

                    b.ToTable("Forks");
                });

            modelBuilder.Entity("Sierra.Model.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Sierra.Model.Fork", b =>
                {
                    b.HasOne("Sierra.Model.Tenant")
                        .WithMany("CustomSourceRepos")
                        .HasForeignKey("TenantId");
                });
#pragma warning restore 612, 618
        }
    }
}
